name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show files
      run: ls 
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.2.0
      with: 
       project-path: ..

